# Example YAML config for TransE in LibKGE
model: TransE
dataset: triples.csv
train:
  batch_size: 1000
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  negative_sampling:
    size: 100
valid:
  every: 10
  metrics: [mean_rank, hits@10]